version: '3.7'

services:
  productsup_php:
    container_name: productsup_php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/productsup
  productsup_nginx:
    container_name: productsup_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/productsup
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - productsup_php
